version: 2
sphinx:
  configuration: docs/sphinx/conf.py

build:
    image: testing
    apt_packages:
      - libgirepository1.0-dev  

python:
    version: 3.8
    install:
        - requirements: docs/sphinx/requirements.txt
        - method: pip
          path: .