version: 2
sphinx:
  configuration: docs/sphinx/conf.py

build:
    image: latest
    apt_packages:
      - libgirepository1.0-dev
      - gcc 
      - libcairo2-dev 
      - pkg-config 
      - python3-dev 
      - gir1.2-gtk-3.0

python:
    version: 3.8
    install:
        - requirements: docs/sphinx/requirements.txt
        - method: pip
          path: .
          extra_requirements:
            - docs
            - pycairo
            - PyGObject