steps:
- wget http://ftp.br.debian.org/debian/pool/main/a/aravis/aravis_0.8.6.orig.tar.xz
- wget http://ftp.br.debian.org/debian/pool/main/a/aravis/aravis_0.8.6-1.dsc
- wget http://ftp.br.debian.org/debian/pool/main/a/aravis/aravis_0.8.6-1.debian.tar.xz
- tar xvJf aravis_0.8.6.orig.tar.xz
- cd aravis-0.8.6
- tar xvJf ../aravis_0.8.6-1.debian.tar.xz
- dpkg-buildpackage -rfakeroot -b -uc -us
- cd ..
- sudo dpkg -i *.deb
- sudo apt update
- sudo apt install -y gir1.2-aravis-0.8 aravis-tools aravis-tools-cli 
