version: 2
sphinx:
  configuration: docs/sphinx/conf.py

build:
    image: latest
    apt_packages:
      - libgirepository1.0-dev
      - make 
      - build-essential 
      - libssl-dev 
      - zlib1g-dev
      - libbz2-dev 
      - libreadline-dev 
      - libsqlite3-dev 
      - wget 
      - llvm 
      - libncurses5-dev
      - libncursesw5-dev 
      - xz-utils 
      - tk-dev 
      - libffi-dev 
      - liblzma-dev 
      - python-openssl
      - libcairo2-dev 
      - libjpeg-dev 
      - libgif-dev 
      - debhelper 
      - cmake 
      - gtk-doc-tools
      - libusb-1.0-0-dev 
      - libaudit-dev 
      - libglib2.0-dev
      - libnotify-dev 
      - libgtk-3-dev 
      - libgstreamer-plugins-base1.0-dev 
      - meson
      - python3-pip 
      - python3-dev 
      - intltool 
      - libxml2-dev

python:
    version: 3.8
    install:
        - requirements: docs/sphinx/requirements.txt
        - method: pip
          path: .
