version: 2
sphinx:
  configuration: docs/sphinx/conf.py

build:
    image: latest    

python:
    version: 3.8
    install:
        - requirements: docs/sphinx/requirements.txt
        - method: pip
          path: .