version: 2
sphinx:
  configuration: docs/sphinx/conf.py

build:
    image: latest
    apt_packages:
      - libgirepository1.0-dev
      - python3-gi 
      - python3-gi-cairo 
      - gir1.2-gtk-3.0
      - gir1.2-aravis-0.8

python:
    version: 3.8
    install:
        - requirements: docs/sphinx/requirements.txt
        - method: pip
          path: .