version: 2
sphinx:
  configuration: docs/sphinx/conf.py

build:
    image: latest
    apt_packages:
      - libgirepository1.0-dev
      - python3-gi 
      - python3-gi-cairo 
      - gir1.2-gtk-3.0
      - aravis-tools                   
      - aravis-tools-cli               
      - gir1.2-aravis-0.8              
      - libaravis-0.8-0                
      - libaravis-dev                  
      - libaravis-doc     

python:
    version: 3.8
    install:
        - requirements: docs/sphinx/requirements.txt
        - method: pip
          path: .