version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '3.11'
  apt_packages:
    - libgirepository1.0-dev

python:
  install:
    - requirements: docs/sphinx/requirements.txt
    - method: pip
      path: .
