# -*- coding: utf-8 -*-
from setuptools import setup

from build import *


package_dir = \
    {'': 'python'}

packages = \
    ['lvmcam', 'lvmcam.actor', 'lvmcam.actor.commands', 'lvmcam.flir']

package_data = \
    {'': ['*'], 'lvmcam': ['etc/*']}

install_requires = \
    ['PyGObject>=3.40.1,<4.0.0',
     'astropy>=4.3.post1,<5.0',
     'click-default-group>=1.2.2,<2.0.0',
     'click>=8.0.1,<9.0.0',
     'daemonocle>=1.2.3,<2.0.0',
     'opencv-python>=4.5.3,<5.0.0',
     'sdss-access>=0.2.3',
     'sdss-araviscam>=0.0.5,<0.0.6',
     'sdss-basecam>=0.5.0,<0.6.0',
     'sdss-clu>=1.2.1,<2.0.0',
     'sdss-tree>=2.15.2',
     'sdsstools>=0.4.0']

entry_points = \
    {'console_scripts': ['lvmcam = lvmcam.__main__:lvmcam']}

setup_kwargs = {
    'name': 'sdss-lvmcam',
    'version': '0.1.0',
    'description': 'package for lvmagp',
    'long_description': '# lvmcam\n\n![Versions](https://img.shields.io/badge/python->3.7-blue)\n[![Documentation Status](https://readthedocs.org/projects/sdss-lvmcam/badge/?version=latest)](https://sdss-lvmcam.readthedocs.io/en/latest/?badge=latest)\n[![Travis (.org)](https://img.shields.io/travis/sdss/lvmcam)](https://travis-ci.org/sdss/lvmcam)\n[![codecov](https://codecov.io/gh/sdss/lvmcam/branch/main/graph/badge.svg)](https://codecov.io/gh/sdss/lvmcam)\n\npackage for lvmagp\n',
    'author': 'Mingyu Jeon, Sumin Lee',
    'author_email': 'mgjeon@khu.ac.kr, lxmark888@khu.ac.kr',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/sdss/lvmcam',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.7,<4.0',
}


build(setup_kwargs)

setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
