name: Docker

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      USER: wasndas
      APP: lvmcam
    steps:
      - name: Set docker tags
        id: set-tags
        run: |
          echo ::set-output name=TAG_LATEST::$USER/$APP:latest
          if [[ $GITHUB_REF == refs/heads/main ]]
          then
            echo ::set-output name=TAGS::$USER/$APP:latest
          elif [[ $GITHUB_REF == refs/heads/* ]]
          then
            BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/[\/]/_/g')
            echo ::set-output name=TAGS::$USER/$APP:$BRANCH
          else
            echo ::set-output name=TAGS::$USER/$APP:${GITHUB_REF#refs/tags/}
          fi
      - name: Show tags
        run: echo ${{ steps.set-tags.outputs.TAGS }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Authorise Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # from Secrets
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          no-cache: true
          push: true
          tags: |
            ghcr.io/${{ steps.set-tags.outputs.TAGS }}
            ghcr.io/${{ steps.set-tags.outputs.TAG_LATEST }}
          file: ./container/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
