on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  release:
    name: Build and publish

    runs-on: ubuntu-24.04

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Create release
        uses: taiki-e/create-gh-release-action@v1.9.0
        with:
          title: lvmcam $version
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5.3.1
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.12'

      - name: Build source and dist
        run: |
          uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
